-- USERS
insert into USER (ID,FIRST_NAME,LAST_NAME, EMAIL, PASSWORD) values (1000,'John','Doe','johndoe@mail.com','1234');

-- GENRES
insert into GENRE(ID,DESCRIPTION) values (1000, 'SPORTS');

-- PLATFORMS
insert into PLATFORM (ID,NAME, MANUFACTURER) values (1000,'XBOX360','MICROSOFT');
insert into PLATFORM (ID,NAME, MANUFACTURER) values (2000,'XBOXONE','MICROSOFT');
insert into PLATFORM (ID,NAME, MANUFACTURER) values (3000,'PC','MICROSOFT');
insert into PLATFORM (ID,NAME, MANUFACTURER) values (4000,'PS3','SONY');
insert into PLATFORM (ID,NAME, MANUFACTURER) values (5000,'PS4','SONY');
insert into PLATFORM (ID,NAME, MANUFACTURER) values (6000,'MAC','APPLE');
insert into PLATFORM (ID,NAME, MANUFACTURER) values (7000,'Swift','NINTENDO');
